trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - script: terraform -chdir=terraform/environments/dev init
    displayName: 'Terraform Init'

  - script: terraform -chdir=terraform/environments/dev validate
    displayName: 'Terraform Validate'
